# Generated by Django 4.2.15 on 2024-09-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmodel_size'),
        ('cart_2', '0002_alter_cartitemmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productmodel'),
        ),
    ]
