# Generated by Django 4.2.15 on 2024-09-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productmodel_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XLarge'), ('XXL', 'XXLarge')], default='M', max_length=3),
        ),
    ]
