# Generated by Django 4.2.15 on 2024-09-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='product/img/default.png', upload_to='product/img/'),
        ),
    ]
